service:
  name: substitution-api

plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs12.x
  region: eu-west-1
  account: 878067559319
  timeout: 60

  environment:
    REGION: ${self:provider.region}
    DYNAMO_DB_TABLE: substitutionTable

  iamRoleStatements: ${file(provider_role_statements.yml)}

custom:
  prune: # used for deleting older function versions
    automatic: true
    number: 1 # number of versions to keep
  webpack:
    includeModules: true

functions:
  ReplaceWord:
    handler: src/handlers/SubstituteController.ReplaceWord
    events:
      - http:
          method: post
          path: /replace
  AddWord:
    handler: src/handlers/WordsController.AddWord
    events:
      - http:
          method: post
          path: /add

resources:
  Resources:
    substitutionTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: substitutionTable
        AttributeDefinitions:
          - AttributeName: word
            AttributeType: S
        KeySchema:
          - AttributeName: word
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5